### ISSUE TITLE
[feature]: re-compile packages to CJS

### ISSUE THREAD

**Issue by carlosala** [fission-codes/filecoin#31]
**Is your feature request related to a problem? Please describe.**
Hi! We're trying to use your library `iso-filecoin` in a project with TS that compiles to `commonjs` modules. It'd be great to publish as well the `cjs` version of the package, otherwise we can't use it.

**Describe the solution you'd like**
Using [`@babel/plugin-transform-modules-commonjs`](https://babeljs.io/docs/babel-plugin-transform-modules-commonjs), compile in build process to `commonjs`. This could be another compilation in `dist/`, and using `exports` field in `package.json` discriminate if it's `require`-ing or `import`-ing.

**Describe alternatives you've considered**
I didn't find alternatives.

**Additional context**
Nothing

**Comment by hugomrdias** [comment]
dual packaging is not without risk and its fairly complicated to get right for all possible combinations.
can you explain a bit more your use case and why you need commonjs?

**Comment by carlosala** [comment]
Hi Hugo, thanks for the answer! My use-case is a Typescript project that compiles to `commonjs` target, and then it converts all `import` to `require`.

**Comment by hugomrdias** [comment]
Yeah i got that from your previous message im gonna need a bit more to consider your request or im just going link you to https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c. 
If its already typescript why can't you just change it to compile to esm?

**Comment by carlosala** [comment]
We're integrating it in https://github.com/LedgerHQ/ledger-live, that we don't control and the compilation process is not modifiable.

**Comment by ainhoa-a** [comment]
Hi @hugomrdias our current implementation on Ledger Live uses https://github.com/Zondax/izari-filecoin. We specifically adapted the library to be fully compatible with Ledger Live. Now, given that this library is no longer being maintained in favor of iso-filecoin we would like to adapt LL to communicate with iso-filecoin. The issue described by @carlosala  is currently a blocker for us to complete the transition.

**Comment by hugomrdias** [comment]
i will consider it, let me do some testing i will report back.

**Comment by hugomrdias** [comment]
@carlosala @ainhoa-a can you check v4 please

**Comment by carlosala** [comment]
Hi @hugomrdias, it looks good! I'd say that the only thing missing is adding cjs files to `files` in `package.json` to be published in npm!
Thanks for the work!

**Comment by hugomrdias** [comment]
Ah that's a good point 😅

**Comment by hugomrdias** [comment]
new is going out, im gonna close this please reopen if you find problems

**Comment by carlosala** [comment]
Still missing cjs files, only d.ts were added 😅

**Comment by hugomrdias** [comment]
@carlosala good now?

**Comment by hugomrdias** [comment]
https://unpkg.com/browse/iso-filecoin@4.0.3/dist/cjs/ ok now its right
